### ISSUE TITLE
inst0 这个代表是哪个端口？

### ISSUE THREAD

**Issue by vmvz** [cnxy/VISAInstrument#7]
例如 地址 `TCPIP0::34465A-01899::inst0::INSTR` 我看 pyvisa 的时候， inst0 好像可以用端口代替，一般代表什么端口？

**Comment by cnxy** [comment]
格式参考如下：
TCPIP[board]::host  address[::LAN  device name][::INSTR]

可选字符串 | 默认值
board | 0
LAN device name | inst0
