### ISSUE TITLE
LAN通信 buffer 大小如何修改

### ISSUE THREAD

**Issue by zhhangtaao** [cnxy/VISAInstrument#8]
示波器回读波形时buffer大小为1024 需要分多次才能读取。

程序中有一段
`public const int READ_BUFFER_COUNT = 1024;`
但是没有找到任何引用。

**Comment by cnxy** [comment]
TcpipSession类中有如下方法：
`public bool SetBufferSize(IOBuffers buffers, int size)`
可以对其大小进行修改。
另外，READ_BUFFER_COUNT 是多余的，现已删除。
